//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeniskiTurniri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kolo()
        {
            this.Mec = new HashSet<Mec>();
        }
    
        public int idk { get; set; }
        public int Odrzavanje_idod { get; set; }
        public int OdrzavanjeTurnir_idtur { get; set; }
    
        public virtual Odrzavanje Odrzavanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mec> Mec { get; set; }
    }
}
