//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeniskiTurniri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odrzavanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odrzavanje()
        {
            this.Kolo = new HashSet<Kolo>();
        }
    
        public int idod { get; set; }
        public System.DateTime datpo { get; set; }
        public System.DateTime datzo { get; set; }
        public int Turnir_idtur { get; set; }
    
        public virtual Turnir Turnir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolo> Kolo { get; set; }
    }
}
