//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeniskiTurniri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodaje
    {
        public int Ulaznica_idu { get; set; }
        public int Turnir_idtur { get; set; }
        public Nullable<int> Gledalac_idg { get; set; }
    
        public virtual Ulaznica Ulaznica { get; set; }
        public virtual Turnir Turnir { get; set; }
        public virtual Gledalac Gledalac { get; set; }
    }
}
