//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeniskiTurniri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucestvuje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucestvuje()
        {
            this.Mec = new HashSet<Mec>();
        }
    
        public int Igrac_idig { get; set; }
        public Nullable<int> Nagrada_idn { get; set; }
        public int Turnir_idtur { get; set; }
        public int Oprema_ido { get; set; }
    
        public virtual Igrac Igrac { get; set; }
        public virtual Nagrada Nagrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mec> Mec { get; set; }
        public virtual Turnir Turnir { get; set; }
        public virtual Oprema Oprema { get; set; }
    }
}
