//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeniskiTurniri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulaznica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulaznica()
        {
            this.Prodaje = new HashSet<Prodaje>();
        }
    
        public int idu { get; set; }
        public System.DateTime datom { get; set; }
        public System.TimeSpan vreme { get; set; }
        public int brreda { get; set; }
        public int brsed { get; set; }
        public string tipu { get; set; }
    
        public virtual VipUlaznica VipUlaznica { get; set; }
        public virtual ObicnaUlaznica ObicnaUlaznica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodaje> Prodaje { get; set; }
    }
}
